spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/db_name?createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: uname
      password: pwd
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://localhost:5432/pgdb_name
      username: pguname
      password: pgpwd
      driver-class-name: org.postgresql.Driver


    hikari:
      maxLifetime: 60000
    jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        hbm2ddl:
          auto: update